project_name: agent
before:
  hooks:
  - go get ./...
builds:
- id: non-windows-build
  env:
  - CGO_ENABLED=0
  ldflags:
     - -s -w -X main.VERSION={{.Tag}}
  goos:
    - linux
    - darwin
  goarch:
    - 386
    - amd64
    - arm
    - arm64
- id: windows-build
  env:
  - CGO_ENABLED=0
  ldflags:
     - -s -w -X main.VERSION={{.Tag}}
  goos:
    - windows
  goarch:
    - 386
    - amd64
    - arm

archives:
  - id: non-windows-archive
    builds:
      - non-windows-build
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - README.md
      - install.sh
    replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64

  - id: windows-archive
    builds:
      - windows-build
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - README.md
      - install.ps1
    replacements:
      386: i386
      amd64: x86_64
      windows: Windows

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch

brews:
  - tap:
      owner: semaphoreci
      name: homebrew-tap
    commit_author:
      name: release-bot-agent
      email: contact+release-bot-agent@renderedtext.com
    folder: Formula
    homepage:  https://semaphoreci.com
    description: Semaphore 2.0 agent.
    test: |
      system "#{bin}/agent version"
